# Generated by Django 3.1.1 on 2020-09-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_title', models.CharField(max_length=200, verbose_name='Вид гитары')),
                ('guitar_text', models.TextField(verbose_name='Описание гитары')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст комментария')),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitars.guitar')),
            ],
        ),
    ]
