# Generated by Django 3.1.1 on 2020-09-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='guitar',
            options={'verbose_name': 'Гитару', 'verbose_name_plural': 'Гитары'},
        ),
    ]
